In [1]:
import torch

In [4]:
x = torch.arange(4.0)  # ！！！这里arange(4.0)生成的都是浮点数的   arrange(4)生成的都是整型的
x

tensor([0., 1., 2., 3.])

In [5]:
# requires_grad_() 如果需要计算梯度，那么这个就设置为True，不然就是False
x.requires_grad_(True)
x.grad

In [6]:
y = 2 * torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [7]:
y.backward()     #通过反向传播函数来计算y关于x的每个分量的梯度
x.grad

tensor([ 0.,  4.,  8., 12.])

In [8]:
x.grad == 4*x

tensor([True, True, True, True])

In [9]:
# 默认的情况下 pytorch会累计梯度，我们需要清除之前的值
x.grad.zero_()        #将之前的grad清除
y = x.sum()           #相当于 y == x???
y.backward()
x.grad

tensor([1., 1., 1., 1.])