In [2]:
import torch
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader

In [3]:
a = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5, 6], [
                 7, 8, 9], [1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = torch.tensor([44, 55, 66, 44, 55, 66, 44, 55, 66, 44, 55, 66])
train_ids = TensorDataset(a, b)
# 切片输出
print(train_ids[0:9])
print('=' * 80)

(tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]), tensor([44, 55, 66, 44, 55, 66, 44, 55, 66]))


In [7]:
# 循环取数据
for x_train, y_label in train_ids:
    print(x_train, y_label)

tensor([1, 2, 3]) tensor(44)
tensor([4, 5, 6]) tensor(55)
tensor([7, 8, 9]) tensor(66)
tensor([1, 2, 3]) tensor(44)
tensor([4, 5, 6]) tensor(55)
tensor([7, 8, 9]) tensor(66)
tensor([1, 2, 3]) tensor(44)
tensor([4, 5, 6]) tensor(55)
tensor([7, 8, 9]) tensor(66)
tensor([1, 2, 3]) tensor(44)
tensor([4, 5, 6]) tensor(55)
tensor([7, 8, 9]) tensor(66)


In [8]:
# DataLoader进行数据封装
train_loader = DataLoader(dataset=train_ids, batch_size=4, shuffle=True)
# 注意enumerate返回值有两个,一个是序号，一个是数据（包含训练数据和标签）
for i, data in enumerate(train_loader, 1):
    x_data, label = data
    print(' batch:{0} x_data:{1}  label: {2}'.format(i, x_data, label))

 batch:1 x_data:tensor([[7, 8, 9],
        [1, 2, 3],
        [7, 8, 9],
        [4, 5, 6]])  label: tensor([66, 44, 66, 55])
 batch:2 x_data:tensor([[1, 2, 3],
        [4, 5, 6],
        [4, 5, 6],
        [1, 2, 3]])  label: tensor([44, 55, 55, 44])
 batch:3 x_data:tensor([[1, 2, 3],
        [7, 8, 9],
        [7, 8, 9],
        [4, 5, 6]])  label: tensor([44, 66, 66, 55])
