In [1]:
import torch

In [3]:
a = torch.tensor([2],dtype=torch.float,requires_grad = True)   # a是叶子结点
b = a ** 2  # 而b是一个中间结点  pytorch只会保存叶子结点的计算图，而不会保存非叶子结点的
c = b ** 2

c.backward()      #调用backward就相当于求导

print(a)
print(b)
print(c)

print("a.grad:",a.grad)    # (2 * b) * (2 * a)     其实就是求导的过程
print("b.grad:",b.grad)

tensor([2.], requires_grad=True)
tensor([4.], grad_fn=<PowBackward0>)
tensor([16.], grad_fn=<PowBackward0>)
a.grad: tensor([32.])
b.grad: None


D:\AILearing\App-Setted\envs\pytorch\lib\site-packages\torch\_tensor.py:1083: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at  C:\cb\pytorch_1000000000000\work\build\aten\src\ATen/core/TensorBody.h:482.)
  return self._grad


关于为什么要梯度清零？

In [6]:
a = torch.tensor([2],dtype = torch.float,requires_grad = True)
for i in range(4):
    b = a ** 2
    b.backward()
    print("a.grad:",a.grad)
    print("__________________")

a.grad: tensor([4.])
__________________
a.grad: tensor([8.])
__________________
a.grad: tensor([12.])
__________________
a.grad: tensor([16.])
__________________
